### ISSUE TITLE
Unit testing consistency python - R

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#116]
Should we have a document/issue thread/something where we list the unit tests that we want to have and the expectations of those tests, to be sure that the R and python behave in a similar way?
If have to write tests for R/python, it would be useful for me to know what is done and expected in python/R.
Also, I was thinking about creating an R-unittest label, but probably best to have a general unittest label, to easily find all testing issues.

**Comment by schristley** [comment]
good ideas! My suggestion is a document (i.e. a test specification) versus an issue thread, so that we can keep track of changes over time.

**Comment by javh** [comment]
I'm partial to either an issue or TODO tags inside the appropriate source files.  Both things I'm likely to pay attention to. But really, whatever works best for whomever is writing the tests. :)

**Comment by schristley** [comment]
If you want to be more formal about the process, you should write a short test specification that describes the set of tests to be performed. As this is unit testing, the document is organized around each "unit", which in this case are the functions in the API. Describe what is being tested and what is the expected result, though sometimes the result isn't known.

An aside... People tend to have slightly different definitions for testing, some people consider unit testing to cover only valid behavior, i.e. does the function operate as expected. With functional testing being a larger scope in that you also test error conditions. Some people consider unit and functionality testing to be equivalent terms and covers both valid and invalid behavior. Testing error conditions often greatly increases the number of tests. Another slight distinction is that unit testing is sometimes performed alongside the code itself, while functional testing is performed against an installed version of the code. The former allows testing of internal functions, while the latter verifies that all the proper pieces are installed and that those internal functions are not accessible.

Anyways, here is an example of what I mean by a test specification for the python read function:

`read()`
- pass valid file handle, verify field names, # of rows and row content
- pass invalid file handle, verify exception is thrown
- pass invalid debug parameter, error??
- pass empty file, error??
- pass file missing required fields, verify required fields in row data
- pass file with incorrect boolean value, verify field equals None, warning message?
- pass file with all allowable boolean values, verify fields have correct value
- pass file with incorrect numeric value, verify field equals None, warning message?
- pass file with incorrect integer value, verify field equals None, warning message?
- pass file with incorrect # of columns in row, error??
- pass file with CSV instead of TSV, error??

This can then be typically turned directly into a task list, or maybe create empty test stubs where you copy/paste the test description as a TODO item, docstring, etc. If you have a tool that can generate the test specification from code, you can start directly with empty test stubs. The only issue with this is to insure that if a test is temporarily commented out for some reason, the test doesn't disappear from the test specification document. Regardless, there should be a document that's part of the developer documentation.

**Comment by ssnn-airr** [comment]
Thank you for the detailed comment @schristley . I don't have experience in writing such test specification documents, but I think we should have one to make sure we make the same validations and throw the same warnigs/errors. It will be useful to have centralized definitions of what is valides and decisions like "if a required fill is empty, do we send an error or do we fill it with NULL, or NA...".  My vote goes for let's start one and write it in a way that works well with copy/paste to PyCharm.

**Comment by ssnn-airr** [comment]
If there are no objections, I will proceed to create a document that we can use as starting point.

**Comment by javh** [comment]
No objection from me. And I don't think we need it for release. I think the R package is basically down right now - we can bump detailed unit test to the next version.

**Comment by javh** [comment]
From the call:
1. Add Travis/Actions consistency check, similar to schema files, for unit test data files in python and R. See top level `/tests` folder.
2. Add a pre-build script to copy test data to lang/python and python/R (and `/tests`).

**Comment by franasa** [comment]
76fe85efea27c23 is a draft for the consistency check for the R and Python test files, but before creating a PR I was just wondering where would be the best place for the pre-build script?

**Comment by javh** [comment]
> where would be the best place for the pre-build script?

Good question... `/tests` I guess? Doesn't really seem appropriate, but it's where the file is works with will be.  I guess we could also add a top-level `/scripts` folder.

**Comment by franasa** [comment]
I experimentally added a few simple rsync commands to the `travis.yml` on the `unit_test_sync` branch for both python: https://github.com/airr-community/airr-standards/blob/39c3899627b4d3187c5321b0fd0e2d9413810cc4/.travis.yml#L8-L10 and R: https://github.com/airr-community/airr-standards/blob/39c3899627b4d3187c5321b0fd0e2d9413810cc4/.travis.yml#L52-L54

I am not sure this is the best approach, but if you all consider that it is good enough we probably also would need to:
- define which folder contains the original files that will be copied to the other folder. 
- and review the test files.

**Comment by scharch** [comment]
@javh @franasa should we generate a PR or close as stale?

**Comment by javh** [comment]
I'm gonna go with stale.
