### ISSUE TITLE
Empty 'required' slot in RearrangementSchema and AlignmentSchema

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#121]
@javh I noticed the required slot is empty. We should set  `LazyData: false` or delete the .rda files in the `data` folder. The .rda objets don't have the `required` slot and I suspect they get loaded after the function 'load_schema' is called and then overwrite the RearrangementSchema and AlignmentSchema created by the function using `definitions.yaml`.

**Comment by javh** [comment]
Those `.rda` files are a merge mistake. Yes, they should be deleted. Not sure exactly how/when they got back in there. We can leave `LazyData: true`, even though we won't have any data.

I originally set the schema up as data objects, because that's the proper way.  I switched to the global variables loaded directly from `definitions.yaml` later. Which, is technically bad R behavior, but I think it'll be a lot easier to maintain.

**Comment by ssnn-airr** [comment]
I agree - as 99% of the time, the 1% is the TODO label - with your decision in favor to easier maintenance. I wasn't sure why the .rda files were there, and I didn't want to remove them in case there was a reason for them to be there.

**Comment by javh** [comment]
Coolness. Oh, and we don't need what's in `data-raw` anymore either.

PS:
Those TODO automatically populate a task list in PyCharm. That's my only attachment to them :)

**Comment by javh** [comment]
Removed in 5581a3d.
