### ISSUE TITLE
can we get rid of Alignment schema?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#186]
Now that IgBlast directly outputs the AIRR TSV file, do we want to continue to support a "hit table" Alignment schema or remove it?

**Comment by javh** [comment]
Well, we said it was in-development in the DR-WG paper, but... If there isn't a need, then it shouldn't be a priority. I don't think there isn't any intention of adding it to IgBLAST (pinging @jianye00).  IIRC, this format was also important for partis (pinging @matsen, @psathyrella) - not sure where that stands.

I've no objection to back-burning or cutting the Alignment schema entirely if there isn't a need.

**Comment by psathyrella** [comment]
@javh I'm not sure I've been plugged in enough to be understanding correctly, but I can't think of anything I've used hit tables for. I was recently looking at actually doing the airr-output for partis (sorry...) which is maybe related? and the reason it didn't get done right then is I saw that it uses cigars, rather than gapped sequences, which requires a good bit of infrastructure since at least in my experience different implementations seem to barf on each others' differing definitions of hard and soft clipping.

**Comment by javh** [comment]
IIRC the stated need was for enabling analysis on multiple V(D)J calls. Ie, having a representation that allowed you to report the top 5 hits, all hits over 90% probability, etc, for V, D and J.

As for CIGAR vs gapped sequences, you'll actually need both... For the clipping rules, just follow the docs here:
http://docs.airr-community.org/en/latest/datarep/overview.html

There's some code in [changeo.Alignment](https://bitbucket.org/kleinstein/changeo/src/tip/changeo/Alignment.py) that you might be able to leverage to get most of the way there.  Maybe:

1. Parse the sequence/germline alignments into the format output by `changeo.Alignment.decodeCIGAR`, which is just a list of tuples containing `(operation, length)`. Eg, `[('M', 20), ('D', 1), ('M', 200)]` is one deletion in the middle of 20, 200 matches/mismatches.
2. Use `changeo.Alignment.encodeCIGAR` to make the CIGAR string and `changeo.Alignment.padAlignment` to add the appropriate clipping to the front.

**Comment by scharch** [comment]
> IIRC, the stated need was for enabling analysis on multiple V(D)J calls. Ie, having a representation that allowed you to report the top 5 hits, all hits over 90% probability, etc, for V, D and J.

Yes, this was my understanding, as well.
SONAR uses BLAST to assign V(D)J calls, as well, and multiple equal or near-equal matches are common, especially for methods that only read from FR2 on. Another use case is when there is a large in-del that causes the blast hit to split into 5' and 3' sections -I stitch these back together to create the final alignment, but that causes some amount of information loss. Currently, I am just saving the BLAST tables in a text file for possible later review, but I would definitely support/implement an AIRR Alignment schema if and when that gets finalized. Probably not a high priority at the moment, though.

>There's some code in changeo.Alignment that you might be able to leverage to get most of the way there.

Oooh, thanks -mind if I crib this, too? :-)

**Comment by javh** [comment]
> Oooh, thanks -mind if I crib this, too? :-)

Go for it. That's what it's there for. :)

**Comment by psathyrella** [comment]
> IIRC, the stated need was for enabling analysis on multiple V(D)J calls. Ie, having a 
> representation that allowed you to report the top 5 hits, all hits over 90% probability,
> etc, for V, D and J.

ah, ok. We certainly need a way to output less-likely annotation information (at the moment, this is for gene calls and naive sequences), but my feeling would be that the meaning of any such column would be very implementation dependent. For instance for gene calls every software would presumably have a list of gene:number pairs, but for one method the number might be a match score, another it might be a probability. Already partis has two different methods of calculating these, and while both output numbers in `[0, 1]`, they're calculated quite differently and are only tenuously related to an actual probability.

So, I'd think it would be most natural for less-likely annotation information to be in extra/optional columns. I guess this is inconvenient, since you have to go look up what the column is for each different software, but I'd argue that's a feature, since it forces you to have some idea what the numbers mean (which is good, since I think they mean quite different things for different softwares).


Great! thanks for the links, I'll see about using those.

**Comment by javh** [comment]
@psathyrella, I *think* we have all that covered in the Alignment schema via the `identity`, `score`, `support`, and `rank` fields. If there are more measures that aren't covered by these, then, yeah, add a custom field I think.

**Comment by schristley** [comment]
Ok, thanks for the feedback. Yeah I'd forgotten that Alignment was for reporting more hits versus the top hit, and is structured in a way to report each gene segment alignment separately. I think we need some tools to actually utilize the format to understand if it is sufficient or not, so I'm fine leaving it in the schema as experimental.
