### ISSUE TITLE
Improve type handling of pandas functions in the python library

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#195]
As of v0.24 pandas should now be able to handle integer columns with missing values:
https://pandas.pydata.org/pandas-docs/version/0.24/whatsnew/v0.24.0.html#optional-integer-na-support

Rather than doing the super annoying thing of automatically, and irrevocably, converting an int column to a float when an NaN value is present.  Which, is currently what happens to the DataFrames output by the airr library (eg, `np2_length` is often converted to a float by `airr.load_rearrangement`.)

I think we're going to have to add explicit type declaration to the pandas functions to handle this.

**Comment by franasa** [comment]
I've just created #489 to add the Int64 handling building on the existing code that was commented. It is drafty because `pd.read_csv` fails when the `schema.false-` and `true_values` have the true boolean values listed on them.
I didn't want to mess around with the `io.RearrangementReader` before bringing this up here so for now I just [removed](https://github.com/airr-community/airr-standards/blob/913bc361cd079bfc792282110c155679f6a2422e/lang/python/airr/interface.py#L92) them in a new list as a temporary fix.
I've also simply added a `StringIO()` to pass it on the reader instead of changing it on `io`. If there is a better-desired way to do this please let me know.

**Comment by javh** [comment]
Awesome. Thanks. I'll take a look at this over the weekend.

**Comment by franasa** [comment]
Sure, and sorry I messed up before because my tox test was not properly set. It passes now but you might want to review it might  not be the most elegant solution
