### ISSUE TITLE
optional vs required

### ISSUE THREAD

**Issue by williamdlees** [airr-community/airr-standards#210]
There are various optional fields which are not directly derivable from required fields - for example cdr1, cdr2 and the various n and p fields. Would it not be better to make these required, given that required fields can always be set to null if data is not available? That would send a stronger message that the values should be provided when available, which is surely what we would want.

**Comment by javh** [comment]
We ended up being conservative on required fields, because we didn't want most tools to be forced to output a lot of empty columns. IIRC, the CDR/FWR, N, and P are optional because there's a fair number of alignment tools that report only the CDR3 and we wanted to keep the compliance burden down. 

Not having `sequence_alignment` and `germline_alignment` (or the positions to derive them) has always been a headache. If we have those, it makes the task of extracting the subregions much easier. But, optional/required is fairly arbitrary. We have easily derived fields in the required set for convenience (eg, `locus`) or MiAIRR support (`junction_aa`). 

I dunno though. It's worth discussing more. My opinion is that I'd like to see broad adoption of the current required fields, before we try to encourage alignment tools to provide more detailed output. If we do add more required fields, I'd like to be pretty far in the future.

**Comment by schristley** [comment]
With the new repertoire metadata schema, `repertoire_id` is the primary key that links a rearrangement with its repertoire. Should `repertoire_id` be `required`?

**Comment by javh** [comment]
I think that has resolved itself with the redesign of the requirement levels.
