### ISSUE TITLE
Tell partial sequences right away from rearrangement schema

### ISSUE THREAD

**Issue by rspreafico** [airr-community/airr-standards#309]
If we define whole/complete/full sequences as those spanning the first base of the (germline) V gene until the last base of the (germline) J gene [as per https://github.com/airr-community/airr-standards/issues/11], how to tell right away whether sequences are full length from the [rearrangement schema](http://docs.airr-community.org/en/stable/datarep/rearrangements.html#fields)? One can spot right away sequences with partial 5' end by looking for `v_germline_start` > 1. However, it is harder to do something similar on the 3' end (looking at `j_germline_end`) since the length of different germline J gene varies and is not immediately available.

The use case I have in mind is submissions to IgBlast, with output AIRR format. I recall from long time ago that partial submission to IMGT V-quest do get flagged as partial 5' or partial 3' with a clear label. 

Am I missing a way to easily infer partial 3' from the rearrangement schema? Would there be value in adding two boolean columns for partial 5' and partial 3' sequence flagging?

**Comment by javh** [comment]
No, there isn't an existing field for this. 

Two integer fields specifying the count of missing 5' and 3' nucleotides would also work, and would be consistent with the IMGT custom fields in #268 (the ones named `5prime_trimmed-n nb` and `3prime_trimmed-n nb` in IMGT's table).

Though, this wouldn't be required fields, so that wouldn't address your immediate need.  In the case of IgBLAST, you can get this information directly from the `j_cigar` field because they add the trailing N operator. The N operator at the end will be the number of bases in the reference, but not the query.

**Comment by rspreafico** [comment]
@javh I will look into the `j_cigar` suggestion for my immediate needs, thanks for the suggestion! It would be great if two fields specifying the count of missing 5' and 3' nucleotides were added to the specification, even if marked as optional. Definitely one vote here. Thank you for considering!

**Comment by javh** [comment]
Sure thing. 

PS: 
For the IgBLAST CIGAR you may also have to verify that the trailing S value is 0 in addition to there being an N value. In case the query sequence actually extends beyond the J, but the end few bases get counted as gaps by IgBLAST.

**Comment by javh** [comment]
We discussed this on our monthly call. Turns out, those IMGT fields don't have the same meaning, so we can't kill two bird with one stone. The question came up of whether a single boolean would be sufficient? 

There is currently a `complete_sequences` field (I think #11 was part of defining this field) in one of the sample preparation definitions (NucleicAcidProcessing) that is defined as:

```
complete_sequences:
    type: string
    enum:
        - partial
        - complete
        - "complete+untemplated"
    description: >
        To be considered `complete`, the procedure used for library construction MUST generate sequences that
        1) include the first V segment codon that encodes the mature polypeptide chain (i.e. after the
        leader sequence) and 2) include the last complete codon of the J segment (i.e. 1 bp 5' of the J->C
        splice site) and 3) provide sequence information for all positions between 1) and 2). To be considered
        `complete & untemplated`, the sections of the sequences defined in points 1) to 3) of the previous
        sentence MUST be untemplated, i.e. MUST NOT overlap with the primers used in library preparation.
    example: partial
```

Some potential solutions are:
* Copy this field down to the Rearrangement level. (Something we prefer to do as often as is practical.)
* Create a similar boolean field, such as `complete_vdj` which specifies if the alignment spans the first V to last J codons.
* Stick with the idea of 5' and 3' deletion integer fields.

What's the use case here? Is the distinction between partial 3' and partial 5' useful? Or will sequences simply be filtered out if they are partial in some manner?

**Comment by rspreafico** [comment]
Thanks @javh for advancing the conversation on this request! My own need is for full sequences, so a single boolean field would suffice, but to make it more generally applicable the two-field option looks more attractive to me.

**Comment by scharch** [comment]
As I said on the call, I prefer the simplicity of a single Boolean if there's nota specific use case that needs more info. The question to me is if copying down `complete_sequence` makes sense given the somewhat different meanings at the two levels.

**Comment by rspreafico** [comment]
@scharch That would work for my use case, but I wouldn't want a standard to be modeled only after my specific use case. Would take the opportunity of a change to make sure it's as generally applicable as possible. I can imagine that most of the times users will only care about whether a VDJ sequence is complete or not - so the single boolean will be sufficient most of the times. But I can imagine that sometimes users will want to keep the information on two ends separately. For example, if one wants to determine whether a novel way to profile VDJ recombinations has systematic size bias (which is actually close to my use case), it may be helpful to know on which end missingness occurs more often, so to get clues on how fix the assay.

The drawback of the two booleans is that if one knows that a sequence is partial, but does not know on which end it is missing base calls, then it would be impossible to encode the even partial information at hand. However, it is hard to imagine that if one has the information that the sequence is partial, it does not know how/why that call was made - so in theory this should not happen often.

**Comment by javh** [comment]
The cellranger (10X Genomics) contig annotation output also has a boolean for this purpose (`full_length`), so there's another example use case.

**Comment by scharch** [comment]
> I wouldn't want a standard to be modeled only after my specific use case. Would take the opportunity of a change to make sure it's as generally applicable as possible.

Yes and no. We have always tried to balance having a convenient, flexible standard with avoiding a multiplication of reserved fields. I still think a single boolean is the best approach here.

**Comment by rspreafico** [comment]
@scharch Fine with me, it serves my need well :-)

**Comment by bcorrie** [comment]
> As I said on the call, I prefer the simplicity of a single Boolean if there's nota specific use case that needs more info. The question to me is if copying down `complete_sequence` makes sense given the somewhat different meanings at the two levels.

Far from an expert here, but the repertoire metadata ```complete_sequence``` field applies to all of the sequences in a repertoire (or at least a <repertoire_id, sample_processing_id, data_processing_id> tuple). So a question I would ask is, "is it valuable (and common) to have a study where all sequences are ```complete_sequences``` or not?" It seems that you would only need a boolean flag at the rearrangement level if ```complete_sequences=partial``` at the repertoire level. That is some sequences in the repertoire might be complete and some might not, so you need the flag...

If it would be common for all sequences in a repertoire to be ```complete``` or ```complete+untemplated``` then it would probably be best to keep this at the repertoire level and then add a boolean flag at the rearrangement level that would be used when a repertoire has ```complete_sequences=partial```

If it is uncommon (rare) for all sequences in a repertoire to be ```complete``` then it would make sense to move this field from the repertoire metadata to the rearrangements.

Does that make sense??? 8-)

**Comment by javh** [comment]
> Does that make sense??? 8-)

Yes, but, as @scharch mentioned, `NucleicAcidProcessing.complete_sequences` does have a different meaning, because that field is about whether or not the library prep _can_ lead to amplicons that span the full V(D)J.

This would be at the Rearrangement level where what you get out of the sequencer will definitely be a mixed bag in terms of how complete it is. You can end up with a lot of truncated reads from preps that would be complete (5'RACE preps or 454 sequencing both do this quite often).

> That would work for my use case, but I wouldn't want a standard to be modeled only after my specific use case. Would take the opportunity of a change to make sure it's as generally applicable as possible. 

There are no concrete rules, but we generally prefer not to add a field that's applicable only to a single group/user/tool.  The standard makes only minor restrictions on custom fields (style, no replication, stick to TSV rules), so a tool can always output a field that isn't in the official spec and still be compliant. But, once we get 2-3 instances, then we try to reserve a name. Usually.

I poked around a bit and I don't see an analogous field in the output of IgBLAST, MiXCR, partis, IMGT/HighV-QUEST, Decombinator, or IgRec.

That said, I think I prefer the single boolean as well, because of (a) simplicity and (b) cellranger-vdj.

**Comment by rspreafico** [comment]
Hi @javh thanks for looking into this. Just one thing to mention is that IMGT V-QUEST does have flags for incomplete 5' or 3' (don't know about HighV-QUEST, but I recall V-QUEST had it). 

Yes, IgBLAST does not have that field - my primary use case would be indeed to have the IgBLAST folks update IgBLAST to the newest AIRR standard, if that will include a flag for incomplete rearrangements.

Is the consensus then to add a single boolean to mark an incomplete VDJ sequence?

**Comment by javh** [comment]
> Is the consensus then to add a single boolean to mark an incomplete VDJ sequence?

Well, I would say the consensus is for me to put in a pull request with a single boolean, and then see what the rest of the community thinks. :)

I'll make the PR soon.

**Comment by scharch** [comment]
Not addressed in #315

**Comment by javh** [comment]
Did GitHub just automatically close this because it was mentioned in #315? That's... obnoxious behavior.

**Comment by bussec** [comment]
Github has a number of terms that do this, in this case the `resolve #309` in the initial comment in #315 was the culprit. This only happens for PRs, though.

**Comment by javh** [comment]
PR is up. #327.

**Comment by javh** [comment]
Seems like we have consensus on the definition, so I'm going to merge in the definition in #327.
