### ISSUE TITLE
A couple of thoughts/questions about AIRR_Minimal_Standard_Data_Elements.tsv

### ISSUE THREAD

**Issue by mikessh** [airr-community/airr-standards#31]
Just my 5 cents (assuming I've downloaded a large AIRR dataset and want to parse it):

  - [x] 1. From the table, is unclear whether all of these columns are required or some of them are optional and can be left blank.
  - [x] 2. I think providing an optional column for donor HLA haplotype in `Subject` is important. We must encourage people to share this very useful info.
  - [x] 3. Suppose one has a dataset of tetramer-sorted cells. Should the info go into `CellProcessing.cell_phenotype`?
  - [x] 4. `DataProcessing.quality_thresholds` says "How sequences were **removed** from (4) based on base quality scores". Actually its not always the best case to remove the sequences, starting from our old MITCR paper we've implemented re-mapping for low quality sequences to improve clonotype count quantification. 
  - [x] 5. `Rearrangement.v_call` and other genes that the input is `string`. However, what to do with multiple mappings as sometimes it is not possible to resolve the exact segment? What would be the delimiter for this kind of situation? 
  - [x] 6. `Rearrangement.junction_aa` - what should be put here for non-coding sequences (it says `string`)? Shouldn't the junction fields be limited to NT/AA alphabet?
  - [x]  7. Any guide on how to handle "exotic" rearrangement data such as incomplete IGH D-J found in lymphomas (i.e. no V, no CDR3 in common sense)?

**Comment by BusseChristian** [comment]
1. All of them are required, but some can be `NULL` if the original study did not collect this information.
2. We tried to make MiAIRR agnostic about whether you are dealing with B or T cells. Thus we did not consider it to me "minimal", although I agree that it will be important for T cell studies. I have put it on the suggestion list for MiAIRR v2. However, we will have to discuss whether this information could allow the re-identification of a subject.
3. Yes.
4. Ok. Could you bring this up with Software WG? Set 5 is still the most flexible and we would like to get input about workflow description from you guys on this.
5. The more general question here is, what the usage scenario for set 6 (see #41)? Otherwise, I agree that reporting all tied calls would be cleanest solution, but the is e.g. not supported by GenBank. If all the hits are reported as one string, there needs to be a custom separator.
6. The same sequence range (i.e. including the C & W/F/L residues). This should be straight forward for nucleotides, for AA you need to encode stops in addition and throw away the last (incomplete) codon. Not sure whether this is still covered by the IMGT specification, though. The other issue here again is GenBank, which IIRC stops translation after the first stop. I will put this onto the to do list for the specifications/best practices document.
7. Excellent point, we have not thought about this, will discuss it.

**Comment by bussec** [comment]
Updated the original issue from @mikessh to the current Schema objects.

**Comment by bussec** [comment]
1. **Solved:** We now have an `x-airr.miairr` property for each MiAIRR defined field. This property is either `essential`, `important` or `defined` which is roughly correlates with SHALL, SHOULD or MAY provide, respectively. Detailed definitions can be found in the [AIRR Community Documentation](https://docs.airr-community.org/en/stable/datarep/airr_schema_requirement_levels.html#categories-of-airr-schema-fields).

**Comment by bussec** [comment]
2. **Solved:** There is now a `Subject.genotype` property that holds an `MHCGenotypeSet`.

**Comment by scharch** [comment]
@mikessh @bussec still active?

**Comment by bussec** [comment]
Looking at these points again, I think that we actually can address all of them with the current changes planned for (or already implemented) v1.5. There are however a couple of documentation tasks that would need to be spun-out.

**Comment by bussec** [comment]
3. **Solved:** If the complete population was sorted for being tetramere-positive, this information should be reflected in `CellProcessing.cell_phenotype`. In contrast to this, if the cells were not specifically isolated for binding a given bait but such binding information has been collected experimentally at single-cell resolution (independent of the actual methodology), this should be annotated as part of the `CellExpression` object.

**Comment by javh** [comment]
4. As this is free text, I think it's fine to say "they weren't removed". I update the definition to say "How/if" instead of just "how".
5. This is already in the format definition, which recommends a comma.
6. `X` (unknown) and `*` (STOP) are the accepted codons, so this should be fine.
7. Good point. Though, the standard should handle this fine, as the various `_call` and `sequence_` can be null.
