### ISSUE TITLE
Should facets return 0 values?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#338]
Currently on both the VDJServer and iReceptor ADC API implementation, it looks like if a facets query returns 0 the facet block is not returned. 

curl -s --data @repertoire/pass-facets3_repertoire.json  https://vdjserver.org/airr/v1/repertoire | python -m json.tool

This asks for a count of the number of subjects in a repertoire that are female (note it uses F which isn't the correct controlled vocabulary value). It should either return 1 or 0, depending on if the subject is `female` or not... 

Not sure if that is the best example, but if you consider a better one, say a search on rearrangement for a junction_aa faceted on repertoire_id, I think for each repertoire_id you would want a count for each repertoire_id, including 0 counts where the junction_aa provided is not found...

@schristley thoughts?

**Comment by schristley** [comment]
I'm not sure I understand. The query filters so you only get repertoires for females, then asks for the count (facets) by `repertoire_id`? That will always return 1 for each `repertoire_id` because they are unique (unless there is a bug or incorrect data). If you want the number of repertoires for female then you should put the facets on `subject.sex`.

Thanks for pointing out the `F` versus `female`, I'll fix that.

**Comment by bcorrie** [comment]
Hmm, on further investigation, you are right... Query filters first, then facets on what if found so this is correct... We had a rearrangement filter that was not returning 0 values when it should have, but I can't reproduce the problem and it seems to be behaving now. I added a few rearrangement tests to test facet counting.

**Comment by bcorrie** [comment]
Closing...

**Comment by bcorrie** [comment]
@schristley still a question regarding facets... If a query asks for facets on repertoire_id and filters for repertoire_id to limit the number of repertoire_ids of interest, I would expect to get a facet count for each repertoire_id requested (even if the count is 0). Would you agree?

Currently, the reference implementation does not do this, it appears to filter out the 0 facet count which is not what I would expect...

The current test expects six responses from the rearrangement facet test, one of which is a 0 count on one repertoire_id.
```
$ ./src/ADCtest.sh https://vdjserver.org/airr/v1 rearrangement rearrangement/pass-facets.json

Running test rearrangement/pass-facets.json
ERROR: Expected 6 != 5 records

SUMMARY: 1 of 1 tests failed
```

**Comment by schristley** [comment]
> Would you agree?

Nope. I think the same process applies, the filter is applied, then in the result set, the counts are performed, because there are no records for that repertoire in the result set, it does not show up in the facets count.

> filters for repertoire_id...

I think this is where your confusion lies. You seem to assume that the server "magically knows" the intent of the query, while that might be possible for this very specific type of query, it's not possible in general. And I don't believe that we should be coding in specific behaviors for specific type of queries.

Take this query for example, where I "filter for repertoire_id", which repertoires should have count of 0?

```
{
 "filters": {
        "op":"and",
        "content":[
            {
                "op": "contains",
                "content": {
                    "field": "repertoire_id",
                    "value": "6551"
                }
            },
            {
                "op":"contains",
                "content":{"field":"junction_aa", "value":"LLTL"}
            }
        ]
    },
    "facets": "repertoire_id"
}
```

Lastly, I think the whole point is pretty mute, it is easy enough for the client to check for the repertoire (or whatever their intent is), and if it's missing from the facets, the client can assume zero.

**Comment by bcorrie** [comment]
This seems like it might be confusing to the user. Consider the query:

```
{
 "filters": {  "op":"contains",  "content":{"field":"junction_aa", "value":"LLTL"} },
  "facets": "repertoire_id"
}
```
If this returns no results for a bunch of repertoires, there is no way for the user to know if a repertoire exists and has a 0 count or that the repertoire is not in the repository. The user doesn't know the list of repertoires in advance in this case.

The only way to determine this is the user to ask for the distinct set of repertoire IDs that exist in the repository, then do the above query, join the two results together, and then continue processing...

That seems clunky to me

My natural expectation for the above query would be to get 0 counts for the things I asked for...

**Comment by schristley** [comment]
> This seems like it might be confusing to the user.

What you are saying strikes me as confusing to the user (and confusing to explain). While the current defined behavior is very simple, 1) filter, 2) perform count on the filtered results. What you seem to be implying is that I have to return a count for all values, regardless of the filter.

We are clearly going round and round here. What's the actual use case here? I still don't understand what problem you are trying to solve, can you please specify it exactly? Because this is the generic facets, please describe how it applies to all queryable fields, like `v_call`, `junction_aa`, `junction_aa_length` and etc.

Because according to your logic, this query would require the repository to return 0 for every unique `junction_aa` in the whole database.

```
{
 "filters": {  "op":"contains",  "content":{"field":"junction_aa", "value":"LLTL"} },
  "facets": "junction_aa"
}
```

**Comment by bcorrie** [comment]
Added this to ADC API v1 as this should probably be sorted out... 

The docs currently say: "It provides all values that exist for the field, and the number of records (repertoires or rearrangement) that have this value". I think it leaves it open to interpretation as to whether "all values that exist for the field" means before or after you apply the filters. Your interpretation is based on Mongo's aggregation pipeline where a set of documents that have been filtered are fed into the facet stage, but I don't think that is the only way of thinking of or implementing a counting mechanism for a specific field.

I think that in actual fact neither response is really wrong. Returning a 0 count or returning no field if there is a 0 count are both semantically correct, and I am not sure it is right to enforce either... It depends on implementation... So maybe we just need to clarify this a bit in the docs?

**Comment by bcorrie** [comment]
Hmm, GDC has the following criteria on their facets:

- The filters object's top level operator must be and, and the internal filters must be limited to: =, !=, in, exclude, is, and not.
- The information provided by facets for a given field will disregard any filters applied to that same field.

https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/#facets

The last one seems to imply that the facets should count all entities in the field, no? Not that we want to follow them in this regard, but...

**Comment by bcorrie** [comment]
For kicks (and because I can) I just tried to facet on junction_aa with no filters on 100M odd rearrangements, and Mongo died - running out of memory, with no search on disk enabled 8-)

**Comment by schristley** [comment]
> For kicks (and because I can) I just tried to facet on junction_aa with no filters on 100M odd rearrangements, and Mongo died - running out of memory, with no search on disk enabled 8-)

Was this on the turnkey?

Yeah, facets has been worrying for some time now. I really would prefer that CRWG goes in the direction of minimizing it versus trying to add more features/capabilities to facets. While I think it's great at the repertoire level, it's really troublesome to me for rearrangements. I would even venture to say that repositories should be allowed to either not support facets on rearrangements, or is allowed to reject a query if it feels it's too burdensome. Or maybe just remove it completely from the /rearrangement endpoint to avoid it being abused.

**Comment by bcorrie** [comment]
> > For kicks (and because I can) I just tried to facet on junction_aa with no filters on 100M odd rearrangements, and Mongo died - running out of memory, with no search on disk enabled 8-)
> 
> Was this on the turnkey?

Yes...

**Comment by bcorrie** [comment]
> Yeah, facets has been worrying for some time now. I really would prefer that CRWG goes in the direction of minimizing it versus trying to add more features/capabilities to facets. While I think it's great at the repertoire level, it's really troublesome to me for rearrangements. I would even venture to say that repositories should be allowed to either not support facets on rearrangements, or is allowed to reject a query if it feels it's too burdensome. Or maybe just remove it completely from the /rearrangement endpoint to avoid it being abused.

If we added /stats API to ADC API we could get rid of facets, which might make sense... It is a bit odd that we have an aggregation/counting capability on a search API entry point...

**Comment by bcorrie** [comment]
> I think that in actual fact neither response is really wrong. Returning a 0 count or returning no field if there is a 0 count are both semantically correct, and I am not sure it is right to enforce either... It depends on implementation... So maybe we just need to clarify this a bit in the docs?

So should we just update the docs to say that either/or is OK - that is returning a 0 count is fine, but it is also OK to return no count for 0 counts? That would solve this immediate problem and allow us to close this issue off for ADV API v1.

**Comment by schristley** [comment]
> but it is also OK to return no count for 0 counts?

that's what I've been trying to convince you of this whole time ;-D Yes, please!

**Comment by schristley** [comment]
> If we added /stats API to ADC API we could get rid of facets, which might make sense...

That sounds like you thinking with your iReceptor gateway hat on, versus your AIRR CRWG standards. ADC API V1 doesn't need /stats nor facets (on rearrangements). It did get pulled over from GDC because it seemed like a nice simple thing, but actually now that we've scaled up rearrangements, it's problematic.

And if you're iReceptor hat is stuck ;-D, there are other simpler ways to do the (presumably limited) set of queries it needs. For example, we can add a `rearrangement_count` field to `DataProcessing` object in `Repertoire`.

**Comment by bcorrie** [comment]
> > If we added /stats API to ADC API we could get rid of facets, which might make sense...
> 
> That sounds like you thinking with your iReceptor gateway hat on, versus your AIRR CRWG standards.

It depends on if the AIRR Data Commons is ever going to move beyond finding and downloading 8-)

**Comment by schristley** [comment]
> It depends on if the AIRR Data Commons is ever going to move beyond finding and downloading 8-)

Maybe we should get one of the CRWG chairs to work on that! ;-D

**Comment by bcorrie** [comment]
> > It depends on if the AIRR Data Commons is ever going to move beyond finding and downloading 8-)
> 
> Maybe we should get one of the CRWG chairs to work on that! ;-D

As as effective chair, this would quickly be delegated to someone in the WG 8-)
