### ISSUE TITLE
merge rearrangement_id -> sequence_id

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#340]
`rearrangement_id` was added to have a more global/database context than `sequence_id`, but now having two identifiers for different contexts is really just causing problems. The plan is to eliminate `rearrangement_id` and just use `sequence_id`.

- Data repositories/tools are allowed to overwrite `sequence_id` with their own value in order to satisfy uniqueness within their database/tool processing.

- Tools should not assume that `sequence_id` contains a value that references a sequence in the raw sequencing files.

@bcorrie As the other big data repository implementation, any concerns?

**Comment by schristley** [comment]
Some previous comments [here](https://github.com/airr-community/airr-standards/issues/246#issuecomment-592726359), [here](https://github.com/airr-community/airr-standards/issues/246#issuecomment-592728685) and [here](https://github.com/airr-community/airr-standards/issues/246#issuecomment-592732266)

**Comment by bcorrie** [comment]
Hmmm, from a repository perspective, I don't like allowing the repository to over write things (like `sequence_id`) that the user might provide. The user who loaded it into the repository might require that information for some purpose later... Remember that this field comes from the tool chain (annotation tools, etc) that produced the data... This is particularly true of `sequence_id` isn't it, in the sense that all sorts of crazy stuff gets encoded in the `sequence_id`. The user is OK to change it (as in when they pass it to a tool that processes the sequences) at their will (it is their data), but if there is a user supplied field (in particular one that is generated by an analysis tool) that is loaded into a repository, I don't think the repository should touch it... 

I think the way things are being referenced in https://github.com/airr-community/airr-standards/issues/340#issuecomment-592733833 fit the current description of `sequence_id` - that is, tools are allowed to change it...
```
                Unique query sequence identifier within the file. Most often this will be the input sequence
                header or a substring thereof, but may also be a custom identifier defined by the tool in
                cases where query sequences have been combined in some fashion prior to alignment.
```
From a repository perspective, because it is a user defined field, I don't think sequence_id should be changed by the repository and if we need something that is unique in a specific context, there should be another _id (which is why we have `rearrangement_id`).

**Comment by schristley** [comment]
@javh looks like we are stuck with this confusion forever, unless you have a counter to Brian cuz he pretty much slammed the door shut without offering an alternative.

**Comment by schristley** [comment]
I think you missed the context because you answered the wrong question... What is being discussed is changing the description/definition of `sequence_id` to have a broader context (i.e. not limited to a file) so that repositories aren't required to have a separate _id field. I was expecting an answer more like, "we use `rearrangement_id` in a million places and changing all that to `sequence_id` would be burdensome so ..."

**Comment by schristley** [comment]
@javh ok, so Brian didn't raise any concerns that effect repositories directly, he seemed to say that the tool developers (i.e. us) have total control over `sequence_id`, so we are free to expand the scope of `sequence_id`. We should probably check (vote?) with others to see if there is any issues, but given that tools are using `sequence_id` currently, I don't see a problem.

The only real potential issue I see is, if data is downloaded from a data repository with `sequence_ids`, then a tool changes those `sequence_ids`, the link to the original records in the data repository is lost. However, that's really a straw-man argument as those ids are not fully qualified anyways, we know we need a different solution #246 for that. So nothing is really lost as they are not true links. A slightly different version of that is if you have a clone/tree file and a rearrangement file, both with `sequence_ids` which link to each other, then a tool changes the ids in one file, but not the other, well then the linkage is lost, but I think we can encourage tools to fix those bugs if and when they arise.

**Comment by bussec** [comment]
@schristley could you briefly confirm that `sequence_id` and `rearrangement_id` would refer to the same entity? I.e. that they do not distinguish any level of read collapsing, error correction, etc.. If this would not be that case we would have further input on this topic.

**Comment by schristley** [comment]
> could you briefly confirm that sequence_id and rearrangement_id would refer to the same entity?

They refer to the same entity. The only difference is the scope of uniqueness for the value, `sequence_id` at file level, `rearrangement_id` at repository level, thus we can redefine `sequence_id` so it can be used at both levels and avoid confusion about which id to use when in the data model.

**Comment by javh** [comment]
If a repository lets you download a Rearrangement TSV that doesn't have unique identifiers in `sequence_id`, such as data from multiple samples or repertoires, then that file would be malformed.  `sequence_id` is already supposed to a unique key, so tools would have to go through an extra step to repair the `sequence_id`.

If we want to preserve the original non-unique `sequence_id`, then we could add an optional `sequence_description` field to store annotations.  Same idea as how FASTA headers are currently defined in a lot of cases (eg, SRA) where the id and description are separated by a space and the id is unique.

Still two fields, but they aren't both required. Plus, I think the semantics are better and it will simplify providing pooled samples/repertoires for download, because you won't have to uniquify `sequence_id` after the merge and prior to the download.

**Comment by bcorrie** [comment]
> @javh ok, so Brian didn't raise any concerns that effect repositories directly, he seemed to say that the tool developers (i.e. us) have total control over `sequence_id`, so we are free to expand the scope of `sequence_id`. We should probably check (vote?) with others to see if there is any issues, but given that tools are using `sequence_id` currently, I don't see a problem.

Actually, I think I did raise an issue that effects repositories... 8-) At least in the sense that I don't think that a repository should change an AIRR field that a user loads into the repository. If the user provides an AIRR TSV file with a sequence_id, I believe that if you query for an exact match on that sequence_id you should be able to find it... As a user that is loading data into a repository, that is what I would expect to be able to do.

**Comment by javh** [comment]
> If the user provides an AIRR TSV file with a sequence_id and loads it into a repository, I believe that if you query for an exact match on that sequence_id you should be able to find it... As a user that is loading data into a repository, that is what I would expect to be able to do.

Does this ever happen with sequence data repositories in practice?  It's certainly not the case with SRA or GenBank.

**Comment by bcorrie** [comment]
> If a repository lets you download a Rearrangement TSV that doesn't have unique identifiers in `sequence_id`, such as data from multiple samples or repertoires, then that file would be malformed. `sequence_id` is already supposed to a unique key, so tools would have to go through an extra step to repair the `sequence_id` before they could use the TSV.

As per my comment above, I actually think that this function should be performed by a separate field (aka rearrangement_id). If a repository is mixing together a bunch of rearrangements from a bunch of different studies and providing them in a single file, then I believe the repository should be the one that is responsible for providing identifiers for uniqueness so that tools can tell them apart. That is what we created rearrangement_id for - it is a repository level field for federating data sets from different sources together, and it makes sense that we would need a separate field for this.

I don't understand the desire to combine these two, as it seems to muddy the waters between what the researcher provides, which might be quite important for data provenance (uniqueness within a specific study context), and what the repositories and downstream tools might require (uniqueness on federated data from many studies).

**Comment by javh** [comment]
> If a repository is mixing together a bunch of rearrangements from a bunch of different studies and providing them in a single file, then I believe the repository should be the one that is responsible for providing identifiers for uniqueness so that tools can tell them apart.

But then the values in `sequence_id` must be unique row keys within the TSV or the TSV is non-compliant, so the repository must the change the values in `sequence_id` upon providing the file (assuming they are not already unique keys).

I'm not seeing this is a change to the definition of `sequence_id`, but instead a clarification to the definition that prevents repositories from incorrectly using `sequence_id` as a descriptive label.

**Comment by bcorrie** [comment]
> Does this ever happen with sequence data repositories in practice? It's certainly not the case with SRA or GenBank.

I think it is a bad (very bad?) precedence to have data provided from a researchers in an AIRR TSV file go into a repository and not come out again 8-) I can't speak to SRA and Genbank 8-)

If this is a field that has no meaning for the researcher (a new field) then this is fine, as the repository creates it. It is my understanding that sequence_id has very specific meanings and is used in specific ways by various tools. If a researcher loads data that has been processed by a specific pipeline, they might use that data in specific ways, so I don't think the repository should change it.

**Comment by javh** [comment]
Well, it's good practice to transfer any annotations encoding the `sequence_id` into a separate schema-defined or custom column. 

Embedding annotation in the FASTA header is just something you have to do with FASTA files, because you only have one line of characters to annotate the sequence. So, that stuff does end up in the `sequence_id`, but that's not what the field is for - `sequence_id` is supposed to be a row key, not a mechanism for making nesting columns.

**Comment by scharch** [comment]
@bcorrie I am not convinced. I'm going to basically repeat everything @javh already said, but: SONAR makes no attempt to assign unique `sequence_id`s across projects. If I upload data, the repository is going to have to rename it --but I don't see the benefit of putting that new id into a different field, because doing so would result in returning an invalid TSV to a user who queried for multiple data sets that I uploaded.
It sounds like your answer is to have `rearrangement_id` be the primary key instead of `sequence_id`. But, if so, then the original tool would have needed to supply that field and then the repository would still be overwriting user-input data after all. Or we would have to tell tools to bifurcate and use `sequence_id` as the primary key for primary data sources but `rearrangement_id` as the key for downloaded data. That's just begging for bugs and bad analysis, it seems to me.

> It is my understanding that sequence_id has very specific meanings and is used in specific ways by various tools.

I don't think this is right. It's mostly just a key into the data. To the extent that it might be used to encode things like sequencer, subject, time point, lineage description, what have you: most of those have separate fields to hold that data; to the extent that they don't, I agree with @javh that a description field is a better fit, anyway. Similarly, as far as data provenance, the renamed sequences will still be linked to the original study and data processing, so I don't see a problem.

**Comment by bcorrie** [comment]
> But then the values in `sequence_id` must be unique row keys within the TSV or the TSV is non-compliant, so the repository must the change the values in `sequence_id` upon providing the file (assuming they are not already unique keys).

OK, I think we are confusing a couple of things. My understanding was that it is the same sequence_id that researchers are used to - an id that is unique in a fasta file, which is processed by a tool chain that eventually creates an AIRR TSV file (at this point, the AIRR TSV annotation still has a unique sequence_id). If the AIRR TSV file is associated with a Repertoire JSON file, then each line in the AIRR TSV file is associated with a combination of repertoire_id, sample_processing_id, and data_processing_id to determine the Repertoire from which the sequence came. For me the sequence_id is unique within this file. Note that the actual files are mentioned in the Repertoire metadata (e.g. filename, paired_filename, or data_processing_files). What this means is that the 4-tuple <repertoire_id, sample_processing_id, data_processing_id, sequence_id> uniquely identifies a sequence (since the sequence_id is unique within the file that is processed by the DataProcessing).

It is these links that I think the we should try and maintain from a data provenance perspective. In this case sequence_id is NOT unique within a federate AIRR TSV file that contains Rearrangements from multiple Repertoires. If we change the sequence_id in the repository and/or munge it when it is returned to maintain uniqueness in a file that has a bunch of sequences from multiple repertoires, then we loose the data provenance that I think a researcher would expect...

This problem is solved very simply by our current rearrangement_id...

If we feel that it is not important to maintain what I understand as the researchers common understanding of sequence_id (i.e. the one that starts with the fasta file) and just need a unique identifier from a repository and analysis perspective, then I would suggest we use rearrangement_id and get rid of sequence_id given that I think it will cause confusion (as it did for me 8-)

**Comment by javh** [comment]
> If we change the sequence_id in the repository and/or munge it when it is returned to maintain uniqueness in a file that has a bunch of sequences from multiple repertoires, then we loose the data provenance that I think a researcher would expect...

I don't see that there's a choice. `sequence_id` must be unique row key in the file, by definition. So, if the repo doesn't return a munged/unique `sequence_id`, then it doesn't return a compliant TSV.

> I would suggest we use rearrangement_id and get rid of sequence_id given that I think it will cause confusion.

I think this is too large of a change, because `sequence_id` is already well-defined and commonly used. `sequence_id` is `rearrangement_id` before we had the Rearrangement object. Some relevant stuff over here in the issue that spawned this issue:
https://github.com/airr-community/airr-standards/issues/246#issuecomment-592726359

**Comment by scharch** [comment]
> This problem is solved very simply by our current rearrangement_id...

Again, I don't think this is right, as @javh and I have been describing.

**Comment by bcorrie** [comment]
We discussed this at the DataRep meeting briefly, and if the experts in the crowd that run these tools and pipelines (which is not me!!!) think that sequence_id is not important to the user of the standard from a data provenance perspective (that is the user will not have expectations about the contents of this field and the tools/repositories can do whatever they want with it) then I agree that we don't need both... It was my understanding that sequence_id was a relevant field that should be maintained - and that is where my concern came from...

My understanding is that the suggestion moving forwards is that repositories are free to reset sequence_id to whatever they want when data is loaded and it is sequence_id that provides uniqueness in the repository (just like it does in a file that is processed by a tool). Note part of the confusion for me is that this is exactly what rearrangement_id is/was, implying that sequence_id was not necessarily unique...
```
rearrangement_id: Identifier for the Rearrangement object. May be identical to sequence_id, but will usually be a universally unique record locator for database applications.
```
The other thing I thought I might point out is that we have a nice symmetry between a query that uses the /airr/v1/repertoire endpoint and repertoire_id. The following two queries result in the same result:
```
curl https://vdjserver.org/airr/v1/repertoire/604803755288555030-242ac116-0001-012
```
and
```
curl --data "{"filters":{"op":"=", "content": {"field":"repertoire_id", "value":"604803755288555030-242ac116-0001-012"}}}" https://vdjserver.org/airr/v1/repertoire
```
We have this as well for /airr/v1/rearrangement and rearrangement_id at the moment, but with the removal of rearrangement_id this is no longer is true... The primary key for the /airr/v1/rearrangement entry point will become sequence_id.

**Comment by scharch** [comment]
> this is exactly what rearrangement_id is/was, implying that sequence_id was not necessarily unique

Yes, because the assumption is that tools don't produce UUID's. What's new is that we eventually came back around to deciding that changing the id is a better solution than adding a new field (even if it's still not perfect).

**Comment by javh** [comment]
> We have this as well for /airr/v1/rearrangement and rearrangement_id at the moment, but with the removal of rearrangement_id this is no longer is true... The primary key for the /airr/v1/rearrangement entry point will become sequence_id.

Yeah, if we'd been more prescient we probably would have named `sequence_id` `rearrangement_id` instead, or maybe just called every primary key field `id` instead of `<object>_id`.

**Comment by bcorrie** [comment]
> Yeah, if we'd been more prescient we probably would have named `sequence_id` `rearrangement_id` instead, or maybe just called every primary key field `id` instead of `<object>_id`.

So are we sure this isn't the right way to go... It would be my preference to use rearrangement_id, as that name matches the schema object name and it matches the ADC API entry point... We talk about Rearrangements in all of our documentation, not Sequences...

Both sequence_id and rearrangement_id are in the DataRep spec as published, as is rearrangement_set_id. We have already turfed rearrangement_set_id, so there is precedent for that (BTW, it looks like rearrangement_set_id should be a deprecated field, as it is in the paper but no longer in the spec). I think the issue here is what will create more confusion and problems in the long term? It seems to me like we should change this to rearrangement_id now, as that seems to be the more "correct" name (I am sure you will correct me if I am wrong 8-), take the hit on having the tools change early on in the spec, rather than have a confusing name for a term live on because we made a mistake naming it early on.

For me this is similar to my pinion on changing organism to species (https://github.com/airr-community/airr-standards/issues/266#issuecomment-544593446) - if there is consensus that rearrangement_id is the right name it is better to fix it early on before more people adopt the spec. Otherwise we will have to live with what seems to be a confusing field name...

**Comment by javh** [comment]
The cost/benefit is pretty different. `sequence_id` is a required field that multiple tools are already using and the benefit to changing the name seems pretty minor to me, even if it would be more clear.

Also, `sequence_id` is used as a primary key in Alignment and Node, in addition to Rearrangement. These both do relate back to the Rearrangement record as the primary record, but they also don't follow the `<object>_id` pattern, so it doesn't seem that wrong.

**Comment by schristley** [comment]
> sequence_id is a required field that multiple tools are already using and the benefit to changing the name seems pretty minor to me.

The more proper thing would be to change the ADC API from /rearrangement to /sequence as it's the unpublished standard... Now getting somebody to make all those changes...

> nice symmetry

symmetry is over-rated anyways, any good spec needs some legacy quirks in it, kind of like wine stains on your favorite coffee table ;-D

**Comment by bcorrie** [comment]
> symmetry is over-rated anyways, any good spec needs some legacy quirks in it, kind of like wine stains on your favorite coffee table ;-D

Arggh, my kingdom for an elegant standard!!! Of course I don't have a kingdom, so that doesn't get me too far...

I think I would prefer to leave /rearrangement as the entry point, and have the lack of symmetry... Having an API entry point matching the documentation and terminology is important...

**Comment by schristley** [comment]
> Arggh, my kingdom for an elegant standard!!! Of course I don't have a kingdom, so that doesn't get me too far...

Well maybe you can resolve it to your satisfaction with #347 as the `_id` field isn't sufficient anyways to be a true DOI according to FAIR (or at least how I interpret it).
