### ISSUE TITLE
Refactor merge_rearrangement() so it can handle many files

### ISSUE THREAD

**Issue by jeromejaglale** [airr-community/airr-standards#451]
`merge_rearrangement()` fails with a few thousand files because it tries to open all files at once and reaches the system limit of 1024 files (on Ubuntu 16.04):
`readers = [RearrangementReader(open(f, 'r'), debug=debug) for f in in_filenames]`

I think it needs a bit of refactoring so it processes the input files one by one?

**Comment by javh** [comment]
This part should work as a generator (one file at a time) instead of a list comprehension. Assuming we change how the function scans the field names of the files to identify the intersection/union of field names across all files. Ie, doing one pass to get the headers and define the output fields, then a second pass to write the merged data.

**Comment by bcorrie** [comment]
@javh @schristley would either of you have any time to look at this? I believe you were the original authors of this so that might be quickest? If not we can get @lfunderburk to investigate a fix. This is on a critical path for us to getting downloads from VDJServer working, so we want to get this sorted out...

**Comment by javh** [comment]
I might have time Sunday. I think it'll be an easy fix, but I won't know until I try...

**Comment by lfunderburk** [comment]
Thank you @javh 
I can also help with refactoring on a forked copy of this repository and creating a PR for you to review next week with a possible modification. 
Will keep an eye on this issue, so if I can help with this, let me know.

**Comment by javh** [comment]
@lfunderburk that also works. :)

My guess is that it's just a matter of changing line 140 in interface.py to:

```
readers = (RearrangementReader(open(f, 'r')) for f in in_filenames)
```

And then adding the following before line 150 (reset readers as a generator instead of list):

```
readers = (RearrangementReader(open(f, 'r'), debug=debug) for f in in_filenames)
```

That's the first thing I'd try at least...

**Comment by javh** [comment]
I pushed a potential fix to master. Could someone test, please?  I did a small test and it still seems to work.

I pushed to master instead of doing a pull request (as is protocol) completely by accident... Sorry about that. It's a small change though, so I just left it instead of backing it out.

**Comment by bcorrie** [comment]
@jeromejaglale can you test this on the Gateway - you will need to get the AIRR python library from the master branch rather than from the package.

**Comment by bcorrie** [comment]
@javh we tested this with a merge of 2,225 files and it worked. Don't ask why we need to merge 2,225 files 8-) This surpassed the Unix file handle limit, so I think your fix solved the problem... I think you can close this if you like and if something else crops up we will open a new issue...
