### ISSUE TITLE
How to store consensus quality scores

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#479]
Our db stores a consensus quality fastq string for each consensus sequence generated from the scireptor pipeline. I couldn't find anything explicit on the schema. So I was wondering, is there a way to store this information or should we create our own custom field for that?

**Comment by ssnn-airr** [comment]
I am also interested in this. I am currently using `sequence_alignment_score` to store comma separated sequencing quality scores, and `sequence_alignment_phred` to store the ascii values.

**Comment by scharch** [comment]
We don't generally distinguish between rearrangements that are derived from a single physical read and those that are a consensus or otherwise bioinformatically generated from multiple reads. So either way, I would recommend a custom field like `sequence_phred`, yes.
@ssnn-airr - I do think it would be better to link it to `sequence` rather than `sequence_alignment`, unless maybe you really only have quality scores for the V(D)J portion? I'm also not crazy about making a `*_score` field that isn't about alignment quality like the existing `v_score` etc.

**Comment by ssnn-airr** [comment]
@scharch In my use case I need the aligned sequencing qualities. It is helpful in some cases, to decide if a 'suspicious' novel polymorphism was detected due to lower sequencing quality at a particular position.

**Comment by javh** [comment]
I would prefer just the Phred ASCII representation. The comma delimited numeric scores sounds more like a custom field, because it deviates from the no-nesting guideline (as much as possible).

What about `quality` (maps to `sequence`) and `quality_alignment` (maps to `sequence_alignment` and `germline_alignment`)?

**Comment by javh** [comment]
From the call:
* @franasa will put in a PR.
* Restrict the definition to Sanger/Phred quality scores: Phred quality scores from 0 to 93 are encoded using ASCII 33 to 126. (Used by Illumina after 2011.)

**Comment by franasa** [comment]
I have simply added those two properties on the rearrangement object, @all/ you might like to review/edit them. 
@sussanna, does this address your case? we were wondering if the alignment that you mention is done against a germline db or rather an operation on your raw reads.

**Comment by ssnn-airr** [comment]
@franasa I think this will work. I can change `sequence_alignment_quality`, and use `quality_alignment`.

I hope this clarifies the 'alignment' part. [`tigger::findNovelAlleles`](https://tigger.readthedocs.io/en/latest/topics/findNovelAlleles/) uses `sequence_alignment` (from IgBLAST or IMGT gene assignment) to identify polymorphic positions in the v region (currently until position 312). Basically it groups sets of sequences assigned a particular allele and analyzes the mutations at each position of `sequence_alignment` (up to 312) in that set of sequences. There is no new alignment, we use the IMGT positions. We now want to be able to use the sequencing quality for each IMGT position.
