### ISSUE TITLE
vignette/README consitency R/python

### ISSUE THREAD

**Issue by imkeller** [airr-community/airr-standards#501]
The vignettes of the python and R packages are quite different. I found it difficult to understand which function in R corresponds to which function in python. Using a consistent structure and nomenclature for the two vignettes would make it easier to understand.

**Comment by ssnn-airr** [comment]
Also the unit testing should be exactly the same. My interpretation of the status of things is that the R package has been neglected because of life in 2020, and because most of the current users are using python, and they have developing the python package and adding functionality as they have needed it.

**Comment by imkeller** [comment]
Yes, the unit testing should also be the same (#116). The python vignette has more functions. But the R vignette has more references and explanation, which might be good if it should be used at some point as a stand-alone Bioconductor package.

**Comment by javh** [comment]
Our own microcosm of the subtle the cultural differences between python and R users. :)

**Comment by javh** [comment]
Closing as stale.
