### ISSUE TITLE
characterize the custom schema attributes in OGRDB

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#518]
Decide which can/should be made part of `x-airr`.

**Comment by williamdlees** [comment]
In 517 you are asking which objects in the OGRDB schema are relevant to a germline gene reference set. Here I think you must be asking what other objects in the OGRDB schema should go into the z-airr schema. I don't think there are any.

**Comment by schristley** [comment]
Not objects per se, but additional attributes on the objects and/or properties. From a quick skim of the [schema](https://github.com/airr-community/gldb-wg/blob/master/germline_schema/schema/receptor_germline_schema.yaml), I see `occurrence`, `rows`, `width`. Maybe they are not needed and can be removed. The `type` of many of the properties will need to be cleaned up too.

**Comment by williamdlees** [comment]
I thought I'd rmoved all the row and width attributes: they are gone now. The preamble (discriminator, type, occurrence) was modelled on the AIRR schema at the time this one was first put together, it can be updated to whatever is used now. The types, I think, are best updated when we complete a review of the content of the schema, because they contain useful information that will need to be documented elsewhere, should we choose to keep the attributes.

**Comment by schristley** [comment]
Hi @williamdlees , created this issue in case there were OGRDB specific attributes that you might want in the schema as optional attributes. I think you indicated there probably won't need to be any? If you still believe so then we can close this issue.

**Comment by williamdlees** [comment]
Thanks, I think we should close this now.
