### ISSUE TITLE
There are two of each object in definitions.yaml

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#53]
Is it possible to deduplicate the objects in definitions.yaml?  Is this a temporary situation?

**Comment by schristley** [comment]
Unknown. It isn't clear if pyyaml supports $ref for referencing other objects.

**Comment by laserson** [comment]
It should support having "$ref" as long as it's valid YAML.  It just won't know anything about the semantics.  Is it necessary to understand the references in this context?

**Comment by schristley** [comment]
Okay, well, I might have misinterpreted your initial question. The difference between the two object definitions is that one exactly matches the MiAIRR spec (i.e. the MiAIRR_* objects), while the other contains fields for the relationship between objects (e.g. subject_id in the sample object to link the associated subject). Christian has indicated that he doesn't want those relationship fields to be in the MiAIRR spec, as he considers them an implementation (database) detail. So if we combine the two objects, then we need some way to indicate which fields technically included in the MiAIRR spec and which ones are not. I suppose it's also up for debate whether we define those relationship fields, but I think we should.

My initial interpretation of your question was whether the fields within the two object (e.g. v_call in both MiAIRR_Rearrangement and Rearrangement) needed to be duplicated. For swagger, you can use `$ref` along with `allOf` to perform object inheritance, so Rearrangement could have a `$ref MiAIRR_Rearrangement` to pull in those fields. For example, check how iReceptor pulls in those definitions and combines them together to create a [response object](https://github.com/sfu-ireceptor/api/blob/AIRR-compliance/iReceptor_Data_Service_API_V2.yaml#L42). And yes, it needs to interpret the semantic, so the airr-formats reference library would need to interpret `$ref`, load the referenced object, then compose the objects.

**Comment by laserson** [comment]
My strong preference would be for there to be just a single object. It's confusing that there are two, and it means that two places in the file need to be updated any time a change is made, which has the potential for errors. I think we could probably stash the "extra" fields into another sub-dict of the objects.

**Comment by schristley** [comment]
I agree with your preference, I don't like the two either. So the OpenAPI spec allows for [extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#specification-extensions), my suggestion is that we add "x-miairr" which is a boolean value, default=false, that indicates the field is part of the MiAIRR standard. Then we can have a single object schema. For example, in the following rearrangement snippet `germline_database` and `v_call` are indicated as MiAIRR standard fields while `v_score` is not.

```
Rearrangement:
   type: object
   properties:
      germline_database:
        x-miairr: true
        type: string
      v_call:
        x-miairr: true
        type: string
      v_score:
        type: number
        description: V alignment score

```

**Comment by schristley** [comment]
@bcorrie Brian, I'm going to work on this soon, which will entail a significant change to the specification. The idea I have is to remove the "double" schema, like `MiAIRR_Rearrangement` and `Rearrangement`, and replace with a single schema where the MiAIRR fields are tagged with a property extension `x-miairr`. You can see an example above the prior comment. This will be for all of the schema objects in the spec. This will obviously impact the iReceptor API. Give it some thought as to if you see any issues. My first thought is that it should be okay because no fields are being removed, essentially just added together into a large schema definition.

**Comment by bcorrie** [comment]
Hi @schristley , this seems reasonable. There will still be higher level objects like "Rearrangements" as in the comment above, correct? I think in this manner, if we include the YAML in the iReceptor API spec this will simply mean that the iReceptor API will pass around all fields by default (x-miairr and non-x-miairr). I guess this raises the question should the MIAIRR fields not have the extension (since they are the minimal standard) and the non MIAIRR "extension" fields have the extension (x-datarep)? Alternately, should they all have an extension field (x-miairr for MiAIRR and x-datarep) for Data Rep fields)?
