### ISSUE TITLE
Is diagnosis & intervention data really n-to-1 with subject?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#56]
In an earlier meeting, it was mentioned that there could be multiple diagnosis&intervention data records associated with a subject. Furthermore, these records are independent from the sample records associated with a subject, which is a n-to-1 relationship. Is it true that diagnosis & intervention data is n-to-1 with subject?

The reason I ask is because it introduces confusion about how to "flatten" records. For example, with NCBI, the MiAIRR objects are de-normalized into a single BioSample record. If a subject has (say) 3 diagnosis&intervention records, and (say) 5 samples, how many BioSample records is that?

**Comment by BusseChristian** [comment]
Yes, diagnosis & intervention (D&I) data is n:1 with subject. However, I agree that there are number of things that must be clarified:
1. It is not the whole D&I block which has an n:1 relation to subject, but rather subsets of it (e.g. the `disease_*` items or `intervention` & `immunogen`).
2. The use of these field is limited due to the absence of a time stamping mechanism (even if it would jsut be a relative one).
3. As we cannot change the fields for MiAIRR v1 anymore, the best solution would IMO be to flatten/serialize the data of the D&I records into one. This single record would then have a 1:1 relationship with subject (there would still be multiple records to account for multiple samples).
