### ISSUE TITLE
Changes to definitions.yaml

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#66]
Would it be ok to change `definitions.yaml` to be called `airr-standards.yaml` (or something similar)?

Also, could we change it from 3 space tabs to 4 space tabs (or 2 space tabs)?  It's messing with my editor.

**Comment by schristley** [comment]
How about `airr-definitions` or `airr-schema`? I don't like `standards` in the filename exactly because it isn't the standard per se. I called the file `definitions` to match the OpenAPI which calls these definitions and/or schema objects.

Only if you promise to use actual tab characters instead of spaces, I'm running on disk space ;-D   j/k, feel free to change the spacing, I'm fine with it.

**Comment by javh** [comment]
+1 for 4 space character "tabs".

**Comment by javh** [comment]
Indentation fixed in #106.

Decision on renaming the file?

**Comment by javh** [comment]
schema.yaml?

**Comment by schristley** [comment]
schema.yaml is okay, airr-schema.yaml might be better, avoids being too generic just in case services have to drop multiple yamls into the same directory, which tends to happen.

**Comment by javh** [comment]
All right, `airr-schema.yaml`, going once? Any other opinions?

**Comment by schristley** [comment]
going twice...

**Comment by bcorrie** [comment]
Got my vote...

**Comment by bcorrie** [comment]
Opps, hit close and comment not comment 8-)

**Comment by javh** [comment]
Done in #124.
