### ISSUE TITLE
Update version to V1 as described in AIRR meeting

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#68]

**Comment by schristley** [comment]
Well, we don't have the v1.0 tag yet though, we should decide what if anything we want in that tag (#55). Maybe create v1.0.0 now then very soon release v1.0.X with documentation, software, and etc. I'm thinking we don't want to actually be v1.1 until MiAIRR and others have new `standards`. For example, new standards from germline WG or common repository WG being likely candidates.

**Comment by javh** [comment]
We had proposed renaming the current `v0.1.0` tag to `v1.0.0` as this changeset is before the airr-formats merged and reflects v1 of the MiAIRR standards. We would target v1.1.0 as the initial release of the python airr-formats library and spec.

According to the proposed development flow guide, #72, this would move the v1.1 MiAIRR milestone discussed in the meeting to v2.0.0 and the long term v2.0.0 goals to v3.0.0.

**Comment by BusseChristian** [comment]
> this would move the v1.1 MiAIRR milestone discussed in the meeting to v2.0.0
But only if MiAIRR v1.1 actually changes/adds/removes data item, or am I wrong? From my perspective the main work will be on the NCBI implementation, or do you also consider this to be part of MiAIRR?

**Comment by javh** [comment]
Yeah, only if it changes the standard. We were trying to think of a way to version the repo when it contains different projects with difference development speeds. Our initial proposal is:

+ Versions follow x.y.z.
+ x = changes in MiAIRR data items. 
+ y = implementation changes. Ie, airr-formats specifications, addition of new software packages or major software changes. This would include stuff like releasing the airr-formats python package and the NCBI import toolkit.
+ z = minor software changes. Ie, software patches and features additions that don't break backwards compatibility or introduce spec changes. Basically, combining `MINOR` and `PATCH` from [semantic versioning](https://semver.org) into a single increment.

The rules are a bit fuzzy, but moving all MiAIRR data item changes to `x` made the most sense, because it was expected to be the most stable project.

**Comment by schristley** [comment]
> But only if MiAIRR v1.1 actually changes/adds/removes data item, or am I wrong?

With the versioning scheme that we came up with, using the standard MAJOR.MINOR.PATCH system, MiAIRR is tied to the MAJOR number. That means MiAIRR always goes up in increments of 1, so V1, V2, V3, etc. In this perspective, we are thinking of the `Standard`, something that affects the broad AIRR community, and will change infrequently.

The MINOR number is for specification updates, including some changes to data elements. Currently in our mind the `Standards` V1 is defined but the specifications (file formats, possibly some data elements, etc.) are not completely defined, so V1.1 will be the first release of the specifications.

Note if it's not clear, we are differentiating between data elements in MiAIRR versus data elements in the specification files, the latter doesn't change the standard and is mostly internal to the software that is implementing AIRR formats.

**Comment by schristley** [comment]
V1.0.0 tag and release has been created. I've not removed the pre-release v0.1.0 tag as existing software is referencing it.
