### ISSUE TITLE
repertoire_id not found in ADC API

### ISSUE THREAD

**Issue by amoschoomy** [airr-community/airr-standards#701]
I want to download from any of these repertoire ids using the ADC API, but it is not found?

![image](https://github.com/airr-community/airr-standards/assets/59367068/5896a8e9-2bba-41d4-8484-9136fb7bc431)

![image](https://github.com/airr-community/airr-standards/assets/59367068/7f3096f9-ee56-4759-9a33-d700883cb834)

Neither do the other repertoire_id works for the sequences I want to download

**Comment by bcorrie** [comment]
Hello @amoschoomy are you interested in the Repertoires that are in the screen dump from iReceptor from study_id PRJNA312319. The empty query that you are showing is searching VDJServer, which is one of the many repositories in the AIRR Data Commons (ADC). This study is not in the VDJServer repository which is why the query is giving you an empty list.

In order to ensure that you find the data for a Repertoire, you need to search all repositories in the ADC. 

Unfortunately, we don't have a great solution for listing all of the Repositories in the ADC. We are working on a solution to this, but for now we have a simple list of repositories in a file on Github. The original file for this was maintained by the iReceptor project but has recently been added to the AIRR Github repository here:

https://github.com/airr-community/adc-registry/blob/master/ADC-registry.tsv

To correctly find Repertories from this study you would need to search all of the repositories on this list. The iReceptor Gateway does this for you.

I hope that helps, let us know if that works.

**Comment by amoschoomy** [comment]
yes thank you, i was querying from a wrong repository it turns out. the AIRR documentation did not mention there were other data repositories so I did not know about it.

**Comment by bcorrie** [comment]
Thanks for pointing that out, we will update the documentation to make sure that is clear.

**Comment by bcorrie** [comment]
Docs are updated...
