### ISSUE TITLE
NULL-able MiAIRR fields

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#96]
A student in our group has recently started to work out MiAIRR-compliant data exports from our sciReptor databases, which exclusively hold single-cell data. During this process we came across a couple of points, which I will address in this an two additional tickets (#97, #98).

* Are we fine with just a NULL value or would we like to also have a more explict "not applicable" or "not determined" value?
* We already discussed that some fields must not be NULL. How do we store this information in the YAML?
* Should we set all fields to NOT NULL first and then do opt-outs once it becomes clear that the data for this field might not be available for legitimate reasons?

**Comment by schristley** [comment]
Listing a field as `required` is meant to prevent it from having a NULL value, however for strings, the value can still be blank `""`. Note, it is up to any tools and/or GUI to enforce that rule.

I don't think a "not applicable" value offers much info but others like "not collected" or "missing" offer a slight nuance, i.e. we collected this information for some samples but couldn't get it for all of them. If all samples in a study are marked "not collected" then that's not helpful, better to leave the field blank to save space. Personally I don't like using those values because when doing a query on a repository you will need to specify multiple combinations to get the data you want.

**Comment by javh** [comment]
If a field is not required, and is `null`, then I think it should be excluded from the file.  

I think `null` is most appropriate for required missing data. The meaning is pretty universal. `null` in yaml, `NULL` in R, and `None` in Python all mean undefined (no value).

**Comment by BusseChristian** [comment]
Speaking with my MiAIRR hat on: MiAIRR fields are always `required` but some can be `NULL` (data that is simply not available in certain setups but crucial in others). Otherwise we would need to find a new terms for these levels, but IMO `required` transports the message "you have to actively report this field, even if your dog ate the USB stick with the data on it" pretty well.
So could we agree on the following three levels?
* required / not NULL (=> reporting required)
* required / NULL-able (=> reporting required)
* not required / not NULL (=> reporting *not* required, do not report if NULL)

**Comment by bcorrie** [comment]
WRT not collected/missing, the problem here is that this will be reported in various ways. If we wanted to support that, then the spec should probably specify what the possible values are and what they mean. We don't want "not collected" and "missing" to be in two files from two tools and meaning the same thing. As Scott says, things can get messy quickly, especially when trying to make queries or comparisons that capture these edge cases.

I think this is a bit of a slippery slope myself, but the group would know better than I how many fields this might be applied to and how many possible values (and their meanings) there would be. If it is small then it is tractable, if it is complex and varies across fields then maybe we should avoid this?

**Comment by ssnn-airr** [comment]
BioSample uses 'missing', 'not applicable' and 'not collected' (as @schristley  commented before)(https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/). We should probably use these values, because we are submitting to BioSample, and be very specific about their meaning, as @bcorrie says.

**Comment by ssnn-airr** [comment]
I like @BusseChristian encoding of the NULL values from the computational perspective. But I think that when presented to users/submitters, the labels required/suggested/optional are easier to interpret. maybe?

**Comment by bcorrie** [comment]
I also like @ssnn-airr comment about keeping the end user in mind for the meaning (required/suggested/optional) - with clear mappings to what that means technically. Good to be reminded that we need to keep the consumer of the data formats in the forefront 8-)

**Comment by ssnn-airr** [comment]
1. I like `recommended`. See other options here, in [Thesaurus](http://www.thesaurus.com/browse/suggested?s=t). But 'recommended' and 'suggested' are the best, imo.

**Comment by bcorrie** [comment]
@bussec Just to be sure I understand the question, what do you mean by a "keyword" being NULL or Missing. If I understand you correctly, semantically NULL == "missing", is that correct?

So the question is, should the spec:

1) insist on "missing" if a value is NULL in all cases, no NULL (empty string) allowed?
2) insist on NULL (empty string) drop missing from the list of keywords?
3) Handle both with NULL == missing, implying tools need to support both.

From a backend perspective, I think it is six of one, half dozen of another... I think regardless of what we want, we are going to have to handle an empty string - you just know files will have that value in them. It makes sense to me that this be defined very clearly as "NULL". If we are supporting keywords for some fields, then I think making it clear in the spec that NULL is the same thing as "missing" also makes sense, if we agree that semantically they are the same 8-)

**Comment by javh** [comment]
I prefer `required`, `recommended` and `optional` as well. And I think `null` is better than `missing`.

Maybe [`not_applicable`, `unavailable`] for null-like? (`N/A` and `U/A`)

**Comment by schristley** [comment]
Not sure I understand the meaning of `recommended` over `optional`. `recommended` by whom? `recommended` for what?

**Comment by bussec** [comment]
@bcorrie

> what do you mean by a "keyword" being NULL or Missing.

In this case "missing" refers to the keyword itself, so if we have a subject record, like:

```
{
	"subject_id": "SUB856413",
	"synthetic": false,
	"organism": "Homo sapiens",
	"sex": "female",
}
```

then the keyword `organism` would be `NULL` in the following case

```
	"synthetic": false,
	"organism": "",
	"sex": "female",
```
while is it missing here:
```
	"synthetic": false,
	"sex": "female",
```

This is of course different from a `missing` value for the keyword like in

```
	"synthetic": false,
	"organism": "missing",
	"sex": "female",
```

I hope this clarifies what I was asking in question 2.

**Comment by bussec** [comment]
@schristley For me this follows pretty much [RFC2119](https://tools.ietf.org/html/rfc2119):

* `required` keywords MUST NOT be `not_applicable`, `not_determined` or `NULL` as they are critical for even the most basic analysis types (e.g. `species`).

* `recommended` keywords are specified in MiAIRR but there might be valid cases in which their value could be `not_applicable` (e.g. `sex` for a synthetic library) or `not_determined` (e.g. for `age`). This is the situation I was initially referring to as "required but NULL-able".

* `optional` keywords only occur when implementing MiAIRR in frameworks that specify additional keywords (as from the Minimal Standards perspective all MiAIRR fields are either `required` or `recommended`). E.g. in the NCBI implementation, a BioSample record CAN contain other valid BioSample attributes (e.g. `body_mass_index`).

**Comment by bcorrie** [comment]
@bussec I don't think it matters from a repository perspective, in that there will be a mapping that needs to be performed from the repository representation to the API/file/spec representation. Different repositories will do it in different ways. 

From a spec perspective, I believe the intent is to support both NULL:
	"synthetic": false,
	"organism": "",
	"sex": "female",
and missing:
	"synthetic": false,
	"sex": "female",
correct?

**Comment by schristley** [comment]
@bussec Those definitions are useful. OpenAPI doesn't differentiate between `recommended` and `optional`, but its `required` keyword matches. We have the additional issue that different WGs have different views on the fields, i.e. MiAIRR, CRWG and DataRep each have different settings for which fields are required, etc., so we cannot share the OpenAPI settings across all groups. My suggestion then is to have group specific attributes, so for MiAIRR I suggest:

```
x-miairr-requirement: required
x-miairr-requirement: recommended
x-miairr-requirement: optional
```

Right now we are using `required` in the Rearrangement schema for DataRep's view, which is different from what MiAIRR has as `required` for the rearrangements.

**Comment by javh** [comment]
Yeah, I think @schristley is right that we need some custom tags. It's more clutter in the schema, but a lot of little things keep popping up that I think could be resolved with custom tags (sorting and grouping stuff).

Just a quibble, these are distinctly different in my mind:

```
"organism": ""
"organism": null
```

Like `y=0` and `y=x/0`.

**Comment by schristley** [comment]
> Just a quibble, these are distinctly different in my mind:
> "organism": ""
> "organism": null

Yes, and OpenAPI handles this differently for `required`, the first passes `required` while the second does not.

**Comment by bussec** [comment]
I agree that `""` and `NULL` are different from the database perspective, but from the content perspective they provide the same information. Would it be a feasible option to define them a equivalent and automatically replace `""` with `NULL` during the sanity checks?

**Comment by schristley** [comment]
> Would it be a feasible option to define them a equivalent and automatically replace "" with NULL during the sanity checks?

Yes, that should be possible. I do a similar thing in the iReceptor API to reduce the amount of data sent.

**Comment by bcorrie** [comment]
And indeed, I think it is important that the spec be as precise as possible so that when data is shared it is clear about the meaning. This goes full circle back to the keywords question and whether we support a controlled vocabulary for missing data.

I think the important thing is the spec is precise in when things should be used and there should probably be only one way of representing something - at least for the required fields. 

For example, for required fields, it appears we all agree no NULL allowed - you have to provide a value (correct me if I am wrong). I wonder if we should allow "". That is, if it is required, should we ask the provider (repository, tool) to explicitly provide a "missing"/"null" keyword in this case to indicate that they know it is required and that it is missing for this entity? Or should the spec say "" and "missing"/"null" are not allowed for required fields (as I think @bussec implied above).

I think this is most important for required fields, and we can probably loosen things up for non-required fields. That is, we may decide that a field can be completely missing from the file or, if the field is in the file, the field can have null values, empty strings(""), or a "missing"/"null"/"not applicable"/"not gathered" keyword. One question is how far down the enforcement path should the spec go to get rid of multiple representations for the same thing (null == "" == "missing"/"null").

**Comment by javh** [comment]
I would say that `""` and `NULL` are equivalent in the TSV file, with `""` being the official representation for `NULL` in the TSV files. However, the yaml metadata file gives us the power make the distinction... 

I guess what I'm wondering is if we are ever going to use that distinction for anything? If we're just going to convert `""` and `NULL` to `None` (python) or `NA` (R), then we probably don't need to mandate a distinction. Especially if the use case is an expression like `x is None` or `is.na(x)`.

**Comment by schristley** [comment]
The situation seems straight forward when considering the TSV file. As indicated, we can handle the conversion between "" and NULL. We have total control because we read and interpret the spec.

The complication comes in with the web services. If the spec has a field (say `sequence`) as `required` then that becomes enforced in specific ways. For example, this JSON is not valid because the required field is missing:

```
{}
```

This JSON is invalid because even though the field is there, it has a null value.

```
{ "sequence": null }
```

Lastly, this JSON is valid because the field is there and it has a value.

```
{ "sequence": "" }
```

This implies that if a field is marked `required`, yet the value in the database is null, the web service will have to explicitly send back a made-up non-null value (presumably ""), otherwise an error is thrown and that data cannot be returned from the web service. This made-up value is problematic when the data type is something other than a string.

Note it is the OpenAPI middleware that is enforcing the `required` tag, so we don't have much control over the behavior (i.e. it is enforcing the spec).

Now I understand that all of the MiAIRR fields are required (for publication), yet I don't think that translates to them having a `required` tag in the spec.

**Comment by schristley** [comment]
> Speaking with my MiAIRR hat on: MiAIRR fields are always required but some can be NULL (data that is simply not available in certain setups but crucial in others).

Using the `required` tag means that we cannot allow this, at least not specifically a NULL value. Instead we would need a made-up value that indicates NULL like "missing" or "not applicable".

**Comment by bussec** [comment]
Dear all

Thanks everyone for the comments. I will *attempt* to put all of your comments into a slightly more formal framework below:

#### Requirement Levels
* `required`: MiAIRR fields that are critical for even the most basic analysis types (e.g. species, locus). The number of `required` fields will be limited (probably 8-12 for the combined data sets 1-3).
* `recommended`: All MiAIRR fields that are not `required`.
* `optional`:  non-MiAIRR fields occuring in frameworks that specify additional keywords. E.g. in the NCBI implementation, a BioSample record CAN contain other valid BioSample attributes (e.g. body_mass_index).

#### Values (just defined for clarity, I do not intend to coin new terms here)

* `NULL`: As used by SQL. Corresponds to "NA" in R, "none" in Python, "undef" in Perl
* `negative value`: One of a set of predefined terms used to indicate the reason why the information for a given field is lacking. The current `negative value` set contains:
  * `not_applicable`: There is no meaningful value for this key due to study design (e.g. `sex` for a phage library).
  * `not_collected`: Data for this field was not collected during the study,
  * `missing`: Data for field was collected, but is not available now.
* `positive value`: The content actually expected for a given field (e.g. "Mus musculus" for `species`)

#### Processing

* all values that are empty strings ("") or white-space only (/^\s+$/) are
replaced by `NULL`
* all `required` field MUST hold a `positive value`
* all `recommended fields MUST hold a `positive value` OR a `negative value`
* all keys that are `NULL` are removed

**Comment by bussec** [comment]
Hy @bcorrie

> I am no expert, but it seems to me that in some cases it might be a high bar to have a positive value in all required fields?

You are right. But I am currently thinking along the lines of "values" setting the "requirement levels" and not vice versa, i.e. if there is a realistic (and legitimate) reason for a field to hold a `negative value` then this field is `recommended` and not `required`.

> Do we want to insist that required fields have a "positive value"?

IMO, yes. But as i said above, this would only apply to around ten MiAIRR fields. Taking a brief glance a the current list, for data sets 1-4 these would likely include (**not** a final list ):

- `synthetic`
- `organism`
- `sample_type`
- `tissue`
- `single_cell`
- `cell_storage`
- `template_class`
- `library_generation_method`
- `complete_sequences`
- `physical_linkage`

**Comment by schristley** [comment]
@bussec, an update. I've been looking at V3 of the OpenAPI spec (most of the existing work has been based upon V2), and they have added a `nullable` attribute for fields. The combination of `required` and `nullable` provides us with more detail. E.g. for the rearrangements fields, `required=true` and `nullable=true` covers our current behavior. For MiAIRR fields, `nullable=false` would insist that the fields have a value, though I believe that it is still the case that an empy string "" is considered a value.

**Comment by bussec** [comment]
@schristley, thinking about how to encode this information in a unified YAML (as per #29) and in regard to your comments from [April 9](https://github.com/airr-community/airr-standards/issues/96#issuecomment-379788989) and [July 31](https://github.com/airr-community/airr-standards/issues/96#issuecomment-409371071):

Do you think that the "requirement" information should be encoded in the YAML by using
1. an `x-miairr-requirement` key with `required`, `recommended` and `optional` values, which would then be mapped to the OpenAPI `required` and `nullable` attributes, or
2. two keys (`x-miairr-required` and `x-miairr-nullable`) with boolean values that would directly correspond to the OpenAPI attributes?

**Comment by schristley** [comment]
> Do you think that the "requirement" information should be encoded in the YAML by using

I prefer 2. as it's a direct mapping with OpenAPI versus 1. which requires code logic to translate the attribute.

**Comment by schristley** [comment]
`required` and `nullable` are in the schema now as AIRR attributes.
